### ISSUE TITLE
Cost to washington?

### ISSUE THREAD

**Issue by ericeslinger** [sir-buckyball/boxcars_payoff#5]
I was massaging the data a little (it's easier to deal with as a hash than array for my nefarious purposes) and noticed that the last entry in most of the payout arrays is zero - it looks like the pay to travel to Washington is 0 for most cities. Is this correct?

It looks like there's 67 cities and each payoff array is 67 long. I can transpose the from-washington row into the to-washington column easily enough.

**Comment by sir-buckyball** [comment]
I've confirmed the issue. The original input file has costs for washington and all washington->\* have prices. *->washington seems to have an issue.

It looks like there must have been a bug in the original table conversion. The data set in the html file indeed has 0 everywhere.
